# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs npm build
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
        working-directory: src/archivebrowser
      - run: npm run build
        working-directory: src/archivebrowser
      
      # Runs dotnet publish
      - name: Dotnet Publish
        uses: actions/setup-dotnet@v1.7.2
      - run: dotnet publish -c Release -f netcoreapp3.1 -o ../../netCore -p:PublishReadyToRun=true -p:PublishSingleFile=true --self-contained true -r win-x64
        working-directory: src/Archiver

      # Uploads the build artifacts
      - name: Upload Browser HTML Artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          name: archiveBrowserHtml
          path: src/archivebrowser/dist/
      - name: Upload Archiver EXE Artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          name: archiverExe
          path: netCore/
